### ISSUE TITLE
请问下有相关的代码吗

### ISSUE THREAD

**Issue by KingdeGuo** [Ericwyn/Miaomiaomiao#1]
hello, 看到了您的这个项目. 但是只在项目中看到了结果类, 没有找到生成类及如何使用. 请问您方便更新下项目吗

**Comment by Ericwyn** [comment]
哈哈哈哈, 这个项目尚处于 "新建文件夹" 阶段, 那时候有了这个想法但是一直没填这个坑

**Comment by Ericwyn** [comment]
其实那时候想法很简单, 我们通过扫描各个 .java 文件, 语法解析出来类名/变量名/方法命, 然后将其用 map 形式做一个映射, 映射成一个 1 开始递增的整数, 之后再将各个数字转换成二进制, 并把 1/0/10/01 等和喵/呜/咪/哇 之类的对应, 最后在做一个整体的字符替换

**Comment by KingdeGuo** [comment]
原来是这样~
我今天看到这样一个描述

> 代码混淆（Obfuscation）是将计算机程序的源代码或机器代码，转换成功能上等价，但是难于阅读和理解的形式的行为。

然后就想着找相关代码看一下.
于是找到了这里.
我还想着变成喵喵喵还怎么执行啊哈哈哈
感谢楼主的回复
